name: myshop
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  bottom_navy_bar: ^6.0.0
  status_alert: ^1.0.0
  flutter_spinkit: ^5.1.0
  animated_text_kit: ^4.2.1
  font_awesome_flutter: ^10.1.0
  timeago: ^3.2.2
  eva_icons_flutter: ^3.1.0
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  google_sign_in: ^5.3.2
  firebase_storage: ^10.2.17
  firebase_analytics: ^9.1.9
  url_launcher: ^6.1.2
  image_picker: ^0.8.5+3
#  image_cropper: ^2.0.3
  image_cropper: ^3.0.1
  shimmer: ^2.0.0
  shared_preferences: ^2.0.15
  auth_buttons: ^2.0.4
  cached_network_image: ^3.2.1
  photo_view: ^0.14.0
  syncfusion_flutter_charts: ^20.3.59
  carousel_slider: ^4.2.0
  flutter_stripe: ^7.0.0
  http: ^0.13.5
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_lints:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpeg"
  adaptive_icon_background: "assets/icon_background.png"
  adaptive_icon_foreground: "assets/icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts: 
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
